import {mixin} from './mixin'
import {setProps} from './setProps'

/**
 * @description A function to update an element based on a virtual dom node.
 * @param {HTMLElement} element The element to update
 * @param {object} oldProps The original props used to create the element.
 * @param {object} props New props generated by the virtual dom.
 * @param {boolean} isSVG Whether we are dealing with SVG or not.
 * @returns {undefined} void.
 */
export function updateElement(
    element,
    oldProps,
    props,
    isSVG
  ) {
  for (let prop in mixin(oldProps, props)) {
    if (
      props[prop] !==
      (prop === 'value' || prop === 'checked'
        ? element[prop]
        : oldProps[prop])
    ) {
      setProps(
        element,
        prop,
        props[prop],
        oldProps[prop],
        isSVG
      )
    }
  }
}
